### PR TITLE
Makes status bar alignment configurable

### PR DESCRIPTION
**Pull request by zackschuster**
Coming from [Git Blame](https://marketplace.visualstudio.com/items?itemName=waderyan.gitblame) I'm used to the blame info being on the left. It would be nice to have this option so I can replace Git Blame with GitLens in my [extension pack](https://marketplace.visualstudio.com/items?itemName=zackschuster.vscode-duck-extensions).

Thanks for your time!

### CODE REVIEW

**Comment by eamodio** [comment]
@zackschuster thanks so much for this! Unfortunately I'm in the middle of some other changes to GitLens, but as soon as I finish those off I'll get this integrated.

Thanks again!

**Comment by eamodio** [comment]
Merged -- Thank you!

**Comment by eamodio** [comment]
@zackschuster FYI you can try the new beta here: [v3.5.0-beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v3.5.0-beta). You can find installation instructions here: [Installing Beta Releases](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Beta-Releases)

Thanks again for your contribution!

**Comment by zackschuster** [comment]
@eamodio wanted to let you know that i've officially [included git lens in my extension pack](https://marketplace.visualstudio.com/items?itemName=zackschuster.vscode-duck-extensions). 

thanks again for merging the PR!

**Comment by eamodio** [comment]
@zackschuster awesome -- thanks

**Pull request closed without merging**
