### PR TITLE
Add link to remote commit

### PR DESCRIPTION
**Pull request by mtsmfm**
Hi
Thank you for creating awesome extension 😄 

BTW, I think it is useful if we can open in remote by clicking commit.

screen shot 2017-06-19 at 3 56 13

What do you think?

### CODE REVIEW

**Comment by eamodio** [comment]
@mtsmfm I think this is a great idea and have been thinking about something similar. The issue is that vscode doesn't support `command:` in the hovers right now. But you prompted me to open https://github.com/Microsoft/vscode/issues/29076 and send a PR https://github.com/Microsoft/vscode/pull/29082 :) 

If this gets accepted I will look into adding a similar feature -- although I would have it open the commit details quickpick rather than open in remote as that is more flexible.

Thanks again for your PR and push!

**Comment by mtsmfm** [comment]
@eamodio Thanks quick response!

Hmm, in my environment (vscode Version 1.13.1), this patch works well:

lens

**Comment by eamodio** [comment]
@mtsmfm wow you are right -- I'm always running the Insiders build and it looks like it only doesn't work there -- I'll dig more into it. Thanks!

**Comment by eamodio** [comment]
@mtsmfm Currently it looks like this feature has been pulled because of security concerns with malicious content in hovers -- see https://github.com/Microsoft/vscode/issues/29076

I hope they can be convinced to not pull the feature completely, but instead change it to mitigate the security concerns.

**Comment by eamodio** [comment]
@mtsmfm FYI, I've added this feature to GitLens v5. Thanks again for the PR, but unfortunately given the vscode API changes and the fact that I wanted the hover commands to open the details quick pick -- I'm closing this PR.

**Pull request closed without merging**
