### PR TITLE
feat: support i18n

### PR DESCRIPTION
**Pull request by axetroy**
# Description

refs: #577 

``English`` version has been implemented.

Next, implement the ``Chinese simplified`` version.

These translations are too many and may take several days

The rest is handed over to other people to implement other languages.

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [ ] My changes are based off of the `develop` branch
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [x] My changes include any required corresponding changes to the documentation
- [ ] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [ ] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Comment by eamodio** [comment]
@axetroy is there anything I can do here to help with this effort?

**Comment by L1cardo** [comment]
how is this going ?  is there anything i can do to help with the translation ?

**Comment by eamodio** [comment]
@axetroy Are you still working on this PR?

**Comment by axetroy** [comment]
@eamodio 

I am busy with other things recently.

I am sorry that I can't continue to do this.

Maybe you can continue with this PR, complete the English version first, and then the community will finish the version in other languages.

**Comment by L1cardo** [comment]
Yeah.
Deed an English version first, and I can work on the Chinese version.

**Comment by pgy866** [comment]
@axetroy 好像没有  接盘侠啊，我也好希望有中文 @eamodio

**Pull request closed without merging**
