### PR TITLE
Closes #1257 - Adds commit ordering option

### LINKED ISSUE #1257: Option to list commits in topological order
It looks like gitlens always sorts the commits list by date, as github does. However to me this is inconvenient when reviewing a PR consisting of multiple commits because different commits in a 'train' of commits are interleaved.

So it would be nice to have a way to change this. This would be the equivalent to
```bash
git log --topo-order
```

### PR DESCRIPTION
**Pull request by thewindsofwinter**
# Description

Closes [#1257](https://github.com/eamodio/vscode-gitlens/issues/1257) - Adds topological ordering option for the git log command. See the issue for details.

# Checklist

- [X] I have followed the guidelines in the Contributing document
- [X] My changes follow the coding style of this project
- [X] My changes build without any errors or warnings
- [X] My changes have been formatted and linted
- [X] My changes include any required corresponding changes to the documentation
- [X] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Comment by eamodio** [comment]
@thewindsofwinter Overall this looks great -- thanks for the contribution! I wonder now though, if we should change this setting to be sort of a `gitlens.advanced.commitOrdering`, which could be one of `null` (the default), `date`, `author-date`, `topo`, and then each callsite would take an `ordering` flag. What do you think?

**Comment by thewindsofwinter** [comment]
> @thewindsofwinter Overall this looks great -- thanks for the contribution! I wonder now though, if we should change this setting to be sort of a `gitlens.advanced.commitOrdering`, which could be one of `null` (the default), `date`, `author-date`, `topo`, and then each callsite would take an `ordering` flag. What do you think?

Hello! I'm glad it looks great, and I think in time I should be able to implement the rest in due time. I was wondering if we should merge this (to address laanwj's issue) and then I can create a new issue for what you suggested. School's started up for me so it might take me some time to change the setting, so I thought it might be better to first have this requested feature and then edit the rest later.

Overall it's your call. Thank you for your time, and I'm glad I didn't mess anything up as of yet :D If there's anything I could improve on please let me know, I'm quite new to this!

**Comment by eamodio** [comment]
No worries if you don't have time. I don't want to merge this in directly and then have to change the settings, but I can add on to this PR to add those features, and then merge it. Thanks again for your contribution!!

**Comment by thewindsofwinter** [comment]
Alright, thank you for your time in reviewing this!

**Comment by Shashank-Shastri** [comment]
@eamodio I updated @thewindsofwinter code and added some more code for the option you mentioned. Please have a look here: https://github.com/eamodio/vscode-gitlens/pull/1421. This is my first time contributing, so do let me know if I did something wrong.

Thanks,
Shashank

**Comment by thewindsofwinter** [comment]
> @eamodio I updated @thewindsofwinter code and added some more code for the option you mentioned. Please have a look here: #1421. This is my first time contributing, so do let me know if I did something wrong.
> 
> Thanks,
> Shashank

Thank you! Sorry I couldn't get to it sooner

**Comment by eamodio** [comment]
@thewindsofwinter @Shashank-Shastri 

Thank you so much for your contributions!

Thank you!

**Pull request merged**
